# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "satware® AI: KI-basierte Automatisierung und Softwarelösungen für Unternehmen"
description: "Entdecken Sie die KI-gestützten Lösungen von satware® AI. Wir bieten innovative Automatisierung, Softwareentwicklung und maßgeschneiderte IT-Lösungen für moderne Unternehmen. Optimieren Sie Ihre Prozesse mit unserer Expertise."
baseurl: "" # Lassen Sie dies leer, wenn die Website im Root-Verzeichnis gehostet wird
url: "https://satware.ai" # Die zukünftige URL der Website



# Build settings
theme: minima
assets:
  - "assets/satag.css"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag # Für bessere SEO

# SEO-Einstellungen
lang: de-DE # Sprache der Website
author: satware AG # Autor der Website
logo: /assets/img/satware-ai.svg # Pfad zu Ihrem Logo (falls vorhanden)
social:
  name: satware AG
  links:
    - https://twitter.com/jekyllrb
    - https://github.com/jekyll

# Permalink-Struktur
permalink: /:categories/:title/

# Pagination (falls benötigt)
# paginate: 10
# paginate_path: "/blog/page:num/"

# Collections (falls benötigt)
# collections:
#   services:
#     output: true
#     permalink: /:collection/:name/
#   case-studies:
#     output: true
#     permalink: /:collection/:name/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .github/
  - README.md
  - LICENSE

# Include specific files/folders that would otherwise be excluded
include:
  - .htaccess
  - CNAME
