# Projekt-Informationen
site_name: ''
site_url: https://satware.ai/
site_author: satware AG
site_description: >-
  Entdecken Sie die KI-gestützten Lösungen von satware® AI. Innovative Automatisierung und maßgeschneiderte IT-Lösungen für Ihr Unternehmen.

use_directory_urls: false

# Copyright
copyright: Copyright &copy; 2025 satware AG

# Konfiguration
theme:
  name: material
  font: false
  custom_dir: overrides/
  language: de

  # Dark Mode als Standard (entsprechend satware CI)
  palette:
    scheme: slate
    primary: custom
    accent: custom

  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow



  #font:
    # text: Roboto
    #code: Roboto Mono

  favicon: assets/images/favicon.png
  logo: assets/images/logo.svg
  icon:
    logo: logo

# Plugins
plugins:
  - search
  - minify:
      minify_js: true
      minify_html: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - blog:
      blog_dir: blog
      blog_toc: true
      post_url_format: "{slug}"
      post_date_format: "dd.MM.yyyy"
      archive_toc: true
      # Added exclusion pattern for README.md files
      exclude:
        - "*.txt"
        - "README.md"
  - social


# Erweiterungen
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: satware
      repo: satwareai-mkdocs
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Zusätzliche Konfiguration
extra:
  social:
    - icon: fontawesome/brands/square-facebook
      link: https://www.facebook.com/satwareAG/
      name: satware AG auf Facebook
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/satware.ag/
      name: satware AG auf Instagram
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/satware-ag/?originalSubdomain=de
      name: satware AG auf LinkedIn
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/satwareAG
      name: satware AG auf X
    - icon: fontawesome/brands/xing
      link: https://www.xing.com/pages/satwareag
      name: satware AG auf Xing
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UChfn2XBDE9yfZrWnMzs1k0g
      name: satware AG auf YouTube

  #cards:
  #  font:
  #    text: Assistant
   #   code: Assistant
  #  cards_layout_options:
  #    background_color: "#000"

  generator: false

# CSS-Anpassungen
extra_css:
  - assets/css/custom.css
extra_javascript:
  - assets/js/body-classes.js
  - assets/js/consent.js
  - assets/js/counter-animation.js
  - assets/js/faq.js
  - assets/js/testimonials.js
  - assets/js/wcag.js
  - assets/js/lightbox.js


# Navigation
nav:
  - KI-Agenten:
      - Übersicht: team/index.md
      - Jane Alesi: team/jane.md
      - Amira Alesi: team/amira.md
      - Bastian Alesi: team/bastian.md
      - Bea Alesi: team/bea.md
      - Justus Alesi: team/justus.md
      - Lara Alesi: team/lara.md
      - Luna Alesi: team/luna.md
      - Marco Alesi: team/marco.md
      - Olu Alesi: team/olu.md
      - Theo Alesi: team/theo.md
  - Anwendungen: anwendungen/
  - Webinare: webinare/
  - Workshops: workshops/
  - Preise: zugang/
  - FAQ: faq/
  - Blog: blog/