FROM squidfunk/mkdocs-material:9.6.14
RUN pip install mkdocs-macros-plugin
RUN pip install mkdocs-glightbox
RUN pip install mkdocs-include-markdown-plugin
RUN pip install mkdocs-video
RUN pip install mkdocs-rss-plugin
RUN pip install mkdocs-snippets
RUN pip install mkdocs-exclude
RUN pip install mkdocs-git-revision-date-localized-plugin
RUN pip install mkdocs-redirects
RUN pip install mkdocs-literate-nav
RUN pip install mkdocs-minify-plugin